### ISSUE TITLE
misspelling in README.md

### ISSUE THREAD

**Issue by marstone** [rodsenra/pode#6]
debbeging, should be debugging, occurs twice.

**Comment by rodsenra** [comment]
I could not find it! Perhaps it was corrected before I saw your post. But thank you anyway ;o)

**Comment by marstone** [comment]
not fixed. but sorry i misspelled too in the issue.

check this:
"Omniscient Debbuging - an easier way to find program bugs"

It shoud be "Debugging", twice

**Comment by rodsenra** [comment]
Fixed, thank you once again!
